name: anchor_getx
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get:
  get_storage:
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  google_sign_in: ^5.0.7
  flutter_login_facebook: ^1.6.2
  intl: ^0.18.0
  permission_handler:
  images_picker: ^1.2.11
  url_launcher:
  loggy: ^2.0.3
  badges: ^3.1.2
  socket_io_client: ^2.0.3+1
  dart_nats: ^0.6.2
  audioplayers: ^5.2.1
  chatview: ^1.3.1
  equatable: ^2.0.5
  simple_grouped_listview: ^2.0.0
  grouped_list: ^5.1.2
  flutter_advanced_avatar: ^1.5.0
  emoji_picker_flutter: ^1.6.4

dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/sound/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
    - family: Heebo
      fonts: 
        - asset: assets/fonts/HeeboMedium.ttf
          weight: 500
        - asset: assets/fonts/HeeboRegular.ttf
          weight: 400
